# Generated by Django 2.2.7 on 2021-10-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=20)),
                ('genre_of_book', models.CharField(max_length=100)),
                ('type_of_book', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=20)),
                ('number_of_pages', models.IntegerField()),
                ('price_of_book', models.FloatField()),
                ('cover_of_book', models.ImageField(default='NA', upload_to='static/books/cover_photo/')),
            ],
            options={
                'db_table': 'Books_Master',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('GenreId', models.AutoField(primary_key=True, serialize=False)),
                ('GenreName', models.CharField(max_length=100)),
            ],
        ),
    ]
